import Joi from "joi";

var totalsSchema = Joi.object({
  isCrossYearPeriod: Joi.boolean(),
  totalRetailAmount: Joi.number().required(),
  totalFinalProfit: Joi.number().required(),
  totalProfitMargin: Joi.number().required(),
  totalProductCosts: Joi.number().required(),
  totalInsuranceFee: Joi.number().required(),
  totalPreTaxProfit: Joi.number().required(),
  totalOtherExpenses: Joi.number().required(),
  totalRetailAmountInCurrentYear: Joi.number(),
  totalFinalProfitInCurrentYear: Joi.number(),
  totalProfitMarginInCurrentYear: Joi.number(),
  totalProductCostsInCurrentYear: Joi.number(),
  totalInsuranceFeeInCurrentYear: Joi.number(),
  totalPreTaxProfitInCurrentYear: Joi.number(),
  totalOtherExpensesInCurrentYear: Joi.number(),
  totalRetailAmountInNextYear: Joi.number(),
  totalFinalProfitInNextYear: Joi.number(),
  totalProfitMarginInNextYear: Joi.number(),
  totalProductCostsInNextYear: Joi.number(),
  totalInsuranceFeeInNextYear: Joi.number(),
  totalPreTaxProfitInNextYear: Joi.number(),
  totalOtherExpensesInNextYear: Joi.number(),
}).required();

var skuSchema = Joi.object({
  tax: Joi.number().required(),
  qty: Joi.number().required(),
  isCostPriceSet: Joi.boolean(),
  profit: Joi.number().required(),
  costPrice: Joi.number(),
  costPriceInCurrentYear: Joi.number(),
  costPriceInNextYear: Joi.number(),
  finalProfit: Joi.number().required(),
  profitMargin: Joi.number().required(),
  retailAmount: Joi.number().required(),
  insuranceFee: Joi.number().required(),
  preTaxProfit: Joi.number().required(),
  otherExpenses: Joi.number().required(),
  isInsuranceFeeIncluded: Joi.boolean(),
  additionalInsuranceFee: Joi.number().required(),
  taxInCurrentYear: Joi.number(),
  qtyInCurrentYear: Joi.number(),
  profitInCurrentYear: Joi.number(),
  finalProfitInCurrentYear: Joi.number(),
  profitMarginInCurrentYear: Joi.number(),
  retailAmountInCurrentYear: Joi.number(),
  insuranceFeeInCurrentYear: Joi.number(),
  preTaxProfitInCurrentYear: Joi.number(),
  otherExpensesInCurrentYear: Joi.number(),
  isCostPriceSetInCurrentYear: Joi.boolean(),
  isInsuranceFeeIncludedInCurrentYear: Joi.boolean(),
  additionalInsuranceFeeInCurrentYear: Joi.number(),
  additionalInsuranceFeeIsPaidInCurrentYear: Joi.number(),
  taxInNextYear: Joi.number(),
  qtyInNextYear: Joi.number(),
  profitInNextYear: Joi.number(),
  finalProfitInNextYear: Joi.number(),
  profitMarginInNextYear: Joi.number(),
  retailAmountInNextYear: Joi.number(),
  insuranceFeeInNextYear: Joi.number(),
  preTaxProfitInNextYear: Joi.number(),
  otherExpensesInNextYear: Joi.number(),
  isCostPriceSetInNextYear: Joi.boolean(),
  isInsuranceFeeIncludedInNextYear: Joi.number(),
  additionalInsuranceFeeInNextYear: Joi.number(),
  additionalInsuranceFeeIsPaidInNextYear: Joi.number(),
  isInsuranceFeeIncludedInNextYear: Joi.boolean(),
});

var schema = Joi.object({
  dateFrom: Joi.string().required(),
  dateTo: Joi.string().required(),
  userId: Joi.string().required(),
  skuId: Joi.number().required(),
  reportId: Joi.number().required(),
  skuIndex: Joi.number().required(),
  costPrice: Joi.number(),
  costPriceInCurrentYear: Joi.number(),
  costPriceInNextYear: Joi.number(),
  skuName: Joi.string().required(),
  taxRate: Joi.number().required(),
  year: Joi.number().required(),
  sku: skuSchema,
  totals: totalsSchema,
});

export default schema;
