var { Schema } = require("mongoose");

var booleanOptions = { type: Boolean };
var numberOptions = { type: Number, default: 0 };
var stringOptions = { type: String, required: true };
var nonRequiredNumberOptions = { type: Number, required: false };

var SKUSchema = new Schema(
  {
    skuName: stringOptions,
    qty: numberOptions,
    costPrice: numberOptions,
    revenue: numberOptions,
    sellerPayoutAmount: numberOptions,
    fines: numberOptions,
    returnAmount: numberOptions,
    retailAmount: numberOptions,
    deliveryCost: numberOptions,
    storageCost: numberOptions,
    acceptance: numberOptions,
    deductionOrPayment: numberOptions,
    additionalPayment: numberOptions,
    tax: numberOptions,
    insuranceFee: numberOptions,
    profit: numberOptions,
    preTaxProfit: numberOptions,
    finalProfit: numberOptions,
    profitMargin: numberOptions,
    isCostPriceSet: { type: Boolean, default: false },
    isInsuranceFeeIncluded: booleanOptions,
    averageProfit: numberOptions,
    averageRetailPrice: numberOptions,
    averageStorageCost: numberOptions,
    averageAdvertisingCost: numberOptions,
    schemaVersion: { type: Number },
    id: { type: Number, required: true },
    qtyInCurrentYear: nonRequiredNumberOptions,
    qtyInNextYear: nonRequiredNumberOptions,
    taxInCurrentYear: nonRequiredNumberOptions,
    taxInNextYear: nonRequiredNumberOptions,
    retailAmountInCurrentYear: nonRequiredNumberOptions,
    retailAmountNextYear: nonRequiredNumberOptions,
    returnAmountInCurrentYear: nonRequiredNumberOptions,
    returnAmountInNextYear: nonRequiredNumberOptions,
    revenueInCurrentYear: nonRequiredNumberOptions,
    revenueInNextYear: nonRequiredNumberOptions,
    deliveryCostInCurrentYear: nonRequiredNumberOptions,
    deliveryCostInNextYear: nonRequiredNumberOptions,
    sellerPayoutAmountInCurrentYear: nonRequiredNumberOptions,
    sellerPayoutAmountInNextYear: nonRequiredNumberOptions,
    finesInCurrentYear: nonRequiredNumberOptions,
    finesInNextYear: nonRequiredNumberOptions,
    storageCostInCurrentYear: nonRequiredNumberOptions,
    storageCostInNextYear: nonRequiredNumberOptions,
    acceptanceInCurrentYear: nonRequiredNumberOptions,
    acceptanceInNextYear: nonRequiredNumberOptions,
    deductionOrPaymentInCurrentYear: nonRequiredNumberOptions,
    deductionOrPaymentInNextYear: nonRequiredNumberOptions,
    additionalPaymentInCurrentYear: nonRequiredNumberOptions,
    additionalPaymentInNextYear: nonRequiredNumberOptions,
    insuranceFeeInCurrentYear: nonRequiredNumberOptions,
    insuranceFeeInNextYear: nonRequiredNumberOptions,
    profitInCurrentYear: nonRequiredNumberOptions,
    profitInNextYear: nonRequiredNumberOptions,
    preTaxProfitInCurrentYear: nonRequiredNumberOptions,
    preTaxProfitInNextYear: nonRequiredNumberOptions,
    finalProfitInCurrentYear: nonRequiredNumberOptions,
    finalProfitInNextYear: nonRequiredNumberOptions,
    profitMarginInCurrentYear: nonRequiredNumberOptions,
    profitMarginInNextYear: nonRequiredNumberOptions,
    averageProfitInCurrentYear: nonRequiredNumberOptions,
    averageProfitInNextYear: nonRequiredNumberOptions,
    averageRetailPriceInCurrentYear: nonRequiredNumberOptions,
    averageRetailPriceInNextYear: nonRequiredNumberOptions,
    averageStorageCostInCurrentYear: nonRequiredNumberOptions,
    averageStorageCostInNextYear: nonRequiredNumberOptions,
    averageAdvertisingCostInCurrentYear: nonRequiredNumberOptions,
    averageAdvertisingCostInNextYear: nonRequiredNumberOptions,
  },
  { _id: false }
);

var recordToSchema = new Schema({ year: stringOptions, month: stringOptions, schemaVersion: { type: Number } }, { _id: false });

var reportSchema = new Schema(
  {
    userId: stringOptions,
    reportId: numberOptions,
    dateFrom: stringOptions,
    dateTo: stringOptions,
    totalSellerPayoutAmount: numberOptions,
    totalSold: numberOptions,
    totalFines: numberOptions,
    totalProductCosts: numberOptions,
    totalReturnAmount: numberOptions,
    totalStorageCost: numberOptions,
    totalDeliveryCost: numberOptions,
    totalRetailAmount: numberOptions,
    totalPaidAcceptance: numberOptions,
    totalAdvertisingCosts: numberOptions,
    totalDeductionOrPayment: numberOptions,
    totalAdditionalPayment: numberOptions,
    totalTaxAmount: numberOptions,
    totalInsuranceFee: numberOptions,
    totalProfit: numberOptions,
    totalPreTaxProfit: numberOptions,
    totalFinalProfit: numberOptions,
    totalProfitMargin: numberOptions,
    taxRate: { type: Number, default: 6 },
    nextYearTaxRate: nonRequiredNumberOptions,
    recordTo: { type: recordToSchema, requred: true },
    skus: [{ type: SKUSchema, required: true }],
    schemaVersion: { type: Number },
    crossesTaxYears: { type: Boolean, default: false },
    totalSellerPayoutAmountInCurrentYear: nonRequiredNumberOptions,
    totalSoldInCurrentYear: nonRequiredNumberOptions,
    totalFinesInCurrentYear: nonRequiredNumberOptions,
    totalProductCostsInCurrentYear: nonRequiredNumberOptions,
    totalReturnAmountInCurrentYear: nonRequiredNumberOptions,
    totalStorageCostInCurrentYear: nonRequiredNumberOptions,
    totalDeliveryCostInCurrentYear: nonRequiredNumberOptions,
    totalRetailAmountInCurrentYear: nonRequiredNumberOptions,
    totalPaidAcceptanceInCurrentYear: nonRequiredNumberOptions,
    totalAdvertisingCostsInCurrentYear: nonRequiredNumberOptions,
    totalDeductionOrPaymentInCurrentYear: nonRequiredNumberOptions,
    totalAdditionalPaymentInCurrentYear: nonRequiredNumberOptions,
    totalTaxAmountInCurrentYear: nonRequiredNumberOptions,
    totalInsuranceFeeInCurrentYear: nonRequiredNumberOptions,
    totalProfitInCurrentYear: nonRequiredNumberOptions,
    totalPreTaxProfitInCurrentYear: nonRequiredNumberOptions,
    totalFinalProfitInCurrentYear: nonRequiredNumberOptions,
    totalProfitMarginInCurrentYear: nonRequiredNumberOptions,
    totalSellerPayoutAmountInNextYear: nonRequiredNumberOptions,
    totalSoldInNextYear: nonRequiredNumberOptions,
    totalFinesInNextYear: nonRequiredNumberOptions,
    totalProductCostsInNextYear: nonRequiredNumberOptions,
    totalReturnAmountInNextYear: nonRequiredNumberOptions,
    totalStorageCostInNextYear: nonRequiredNumberOptions,
    totalDeliveryCostInNextYear: nonRequiredNumberOptions,
    totalRetailAmountInNextYear: nonRequiredNumberOptions,
    totalPaidAcceptanceInNextYear: nonRequiredNumberOptions,
    totalAdvertisingCostsInNextYear: nonRequiredNumberOptions,
    totalDeductionOrPaymentInNextYear: nonRequiredNumberOptions,
    totalAdditionalPaymentInNextYear: nonRequiredNumberOptions,
    totalTaxAmountInNextYear: nonRequiredNumberOptions,
    totalInsuranceFeeInNextYear: nonRequiredNumberOptions,
    totalProfitInNextYear: nonRequiredNumberOptions,
    totalPreTaxProfitInNextYear: nonRequiredNumberOptions,
    totalFinalProfitInNextYear: nonRequiredNumberOptions,
    totalProfitMarginInNextYear: nonRequiredNumberOptions,
    currentYearRetailAmount: nonRequiredNumberOptions,
    nextYearRetailAmount: nonRequiredNumberOptions,
    currentYearTaxAmount: nonRequiredNumberOptions,
    nextYearTaxAmount: nonRequiredNumberOptions,
    currentYearInsuranceFee: nonRequiredNumberOptions,
    nextYearInsuranceFee: nonRequiredNumberOptions,
  },
  { _id: false }
);

var reportsSchema = new Schema({
  userId: stringOptions,
  reports: { type: [reportSchema], required: false },
  schemaVersion: { type: Number },
});

module.exports = { SKUSchema, reportSchema, reportsSchema };
