import { Schema } from "mongoose";

var booleanOptions = { type: Boolean };
var numberOptions = { type: Number, default: 0 };
var stringOptions = { type: String, required: true };
var nonRequiredNumberOptions = { type: Number, required: false };

var skuSchema = new Schema(
  {
    skuName: stringOptions,
    qty: numberOptions,
    taxableAmount: numberOptions,
    taxableAmountInCurrentYear: numberOptions,
    taxableAmountInNextYear: numberOptions,
    qtyInCurrentYear: nonRequiredNumberOptions,
    qtyInNextYear: nonRequiredNumberOptions,
    costPrice: numberOptions,
    costPriceInCurrentYear: numberOptions,
    costPriceInNextYear: numberOptions,
    otherExpenses: numberOptions,
    otherExpensesInCurrentYear: numberOptions,
    otherExpensesInNextYear: numberOptions,
    revenue: numberOptions,
    revenueInCurrentYear: nonRequiredNumberOptions,
    revenueInNextYear: nonRequiredNumberOptions,
    sellerPayoutAmount: numberOptions,
    sellerPayoutAmountInCurrentYear: nonRequiredNumberOptions,
    sellerPayoutAmountInNextYear: nonRequiredNumberOptions,
    fines: numberOptions,
    finesInCurrentYear: nonRequiredNumberOptions,
    finesInNextYear: nonRequiredNumberOptions,
    returnAmount: numberOptions,
    returnAmountInCurrentYear: nonRequiredNumberOptions,
    returnAmountInNextYear: nonRequiredNumberOptions,
    retailAmount: numberOptions,
    retailAmountInCurrentYear: nonRequiredNumberOptions,
    retailAmountInNextYear: nonRequiredNumberOptions,
    deliveryCost: numberOptions,
    deliveryCostInCurrentYear: nonRequiredNumberOptions,
    deliveryCostInNextYear: nonRequiredNumberOptions,
    storageCost: numberOptions,
    storageCostInCurrentYear: nonRequiredNumberOptions,
    storageCostInNextYear: nonRequiredNumberOptions,
    acceptance: numberOptions,
    acceptanceInCurrentYear: nonRequiredNumberOptions,
    acceptanceInNextYear: nonRequiredNumberOptions,
    deductionOrPayment: numberOptions,
    deductionOrPaymentInCurrentYear: nonRequiredNumberOptions,
    deductionOrPaymentInNextYear: nonRequiredNumberOptions,
    additionalPayment: numberOptions,
    additionalPaymentInCurrentYear: nonRequiredNumberOptions,
    additionalPaymentInNextYear: nonRequiredNumberOptions,
    tax: numberOptions,
    taxInCurrentYear: nonRequiredNumberOptions,
    taxInNextYear: nonRequiredNumberOptions,
    insuranceFee: numberOptions,
    insuranceFeeInCurrentYear: nonRequiredNumberOptions,
    insuranceFeeInNextYear: nonRequiredNumberOptions,
    additionalInsuranceFee: numberOptions,
    additionalInsuranceFeeInCurrentYear: nonRequiredNumberOptions,
    additionalInsuranceFeeInNextYear: nonRequiredNumberOptions,
    profit: numberOptions,
    profitInCurrentYear: nonRequiredNumberOptions,
    profitInNextYear: nonRequiredNumberOptions,
    preTaxProfit: numberOptions,
    preTaxProfitInCurrentYear: nonRequiredNumberOptions,
    preTaxProfitInNextYear: nonRequiredNumberOptions,
    finalProfit: numberOptions,
    finalProfitInCurrentYear: nonRequiredNumberOptions,
    finalProfitInNextYear: nonRequiredNumberOptions,
    profitMargin: numberOptions,
    profitMarginInCurrentYear: nonRequiredNumberOptions,
    profitMarginInNextYear: nonRequiredNumberOptions,
    isCostPriceSet: { type: Boolean, default: false },
    isCostPriceSetInCurrentYear: { type: Boolean, default: false },
    isCostPriceSetInNextYear: { type: Boolean, default: false },
    isInsuranceFeeIncluded: booleanOptions,
    isInsuranceFeeIncludedInCurrentYear: booleanOptions,
    isInsuranceFeeIncludedInNextYear: booleanOptions,
    averageProfit: numberOptions,
    averageProfitInCurrentYear: nonRequiredNumberOptions,
    averageProfitInNextYear: nonRequiredNumberOptions,
    averageRetailPrice: numberOptions,
    averageRetailPriceInCurrentYear: nonRequiredNumberOptions,
    averageRetailPriceInNextYear: nonRequiredNumberOptions,
    averageStorageCost: numberOptions,
    averageStorageCostInCurrentYear: nonRequiredNumberOptions,
    averageStorageCostInNextYear: nonRequiredNumberOptions,
    averageAdvertisingCost: numberOptions,
    averageAdvertisingCostInCurrentYear: nonRequiredNumberOptions,
    averageAdvertisingCostInNextYear: nonRequiredNumberOptions,
    schemaVersion: { type: Number },
    id: { type: Number, required: true },
  },
  { _id: false },
);

var recordedToSchema = new Schema({ year: { type: Number, required: true }, month: stringOptions, schemaVersion: { type: Number } }, { _id: false });

var reportSchema = new Schema(
  {
    userId: stringOptions,
    reportId: numberOptions,
    dateFrom: stringOptions,
    dateTo: stringOptions,
    totalSellerPayoutAmount: numberOptions,
    totalSold: numberOptions,
    totalFines: numberOptions,
    totalProductCosts: numberOptions,
    totalReturnAmount: numberOptions,
    totalStorageCost: numberOptions,
    totalDeliveryCost: numberOptions,
    totalRetailAmount: numberOptions,
    totalPaidAcceptance: numberOptions,
    totalAdvertisingCosts: numberOptions,
    totalDeductionOrPayment: numberOptions,
    totalAdditionalPayment: numberOptions,
    totalTaxAmount: numberOptions,
    totalInsuranceFee: numberOptions,
    totalOtherExpenses: numberOptions,
    totalTaxableAmount: numberOptions,
    totalTaxableAmountInCurrentYear: numberOptions,
    totalTaxableAmountInNextYear: numberOptions,
    totalOtherExpensesInCurrentYear: numberOptions,
    totalOtherExpensesInNextYear: numberOptions,
    totalAdditionalInsuranceFee: numberOptions,
    totalProfit: numberOptions,
    totalPreTaxProfit: numberOptions,
    totalFinalProfit: numberOptions,
    totalProfitMargin: numberOptions,
    taxRate: { type: Number, default: 6 },
    nextYearTaxRate: nonRequiredNumberOptions,
    recordedTo: { type: recordedToSchema, requred: true },
    schemaVersion: { type: Number },
    buybackReportIsExist: { type: Boolean, default: false },
    isCrossYearPeriod: { type: Boolean, default: false },
    totalSellerPayoutAmountInCurrentYear: nonRequiredNumberOptions,
    totalSoldInCurrentYear: nonRequiredNumberOptions,
    totalSoldInNextYear: nonRequiredNumberOptions,
    totalFinesInCurrentYear: nonRequiredNumberOptions,
    totalProductCostsInCurrentYear: nonRequiredNumberOptions,
    totalReturnAmountInCurrentYear: nonRequiredNumberOptions,
    totalStorageCostInCurrentYear: nonRequiredNumberOptions,
    totalDeliveryCostInCurrentYear: nonRequiredNumberOptions,
    totalRetailAmountInCurrentYear: nonRequiredNumberOptions,
    totalPaidAcceptanceInCurrentYear: nonRequiredNumberOptions,
    totalAdvertisingCostsInCurrentYear: nonRequiredNumberOptions,
    totalDeductionOrPaymentInCurrentYear: nonRequiredNumberOptions,
    totalAdditionalPaymentInCurrentYear: nonRequiredNumberOptions,
    totalTaxAmountInCurrentYear: nonRequiredNumberOptions,
    totalInsuranceFeeInCurrentYear: nonRequiredNumberOptions,
    totalAdditionalInsuranceFeeInCurrentYear: nonRequiredNumberOptions,
    totalAdditionalInsuranceFeeInNextYear: nonRequiredNumberOptions,
    totalProfitInCurrentYear: nonRequiredNumberOptions,
    totalPreTaxProfitInCurrentYear: nonRequiredNumberOptions,
    totalFinalProfitInCurrentYear: nonRequiredNumberOptions,
    totalProfitMarginInCurrentYear: nonRequiredNumberOptions,
    totalSellerPayoutAmountInNextYear: nonRequiredNumberOptions,
    totalSoldInNextYear: nonRequiredNumberOptions,
    totalFinesInNextYear: nonRequiredNumberOptions,
    totalProductCostsInNextYear: nonRequiredNumberOptions,
    totalReturnAmountInNextYear: nonRequiredNumberOptions,
    totalStorageCostInNextYear: nonRequiredNumberOptions,
    totalDeliveryCostInNextYear: nonRequiredNumberOptions,
    totalRetailAmountInNextYear: nonRequiredNumberOptions,
    totalPaidAcceptanceInNextYear: nonRequiredNumberOptions,
    totalAdvertisingCostsInNextYear: nonRequiredNumberOptions,
    totalDeductionOrPaymentInNextYear: nonRequiredNumberOptions,
    totalAdditionalPaymentInNextYear: nonRequiredNumberOptions,
    totalTaxAmountInNextYear: nonRequiredNumberOptions,
    totalInsuranceFeeInNextYear: nonRequiredNumberOptions,
    totalProfitInNextYear: nonRequiredNumberOptions,
    totalPreTaxProfitInNextYear: nonRequiredNumberOptions,
    totalFinalProfitInNextYear: nonRequiredNumberOptions,
    totalProfitMarginInNextYear: nonRequiredNumberOptions,
    isFinancesAccounted: { type: Boolean, default: false },
    skus: [{ type: skuSchema, required: true }],
  },
  { _id: false },
);

var reportsWithAccountedFinancesSchema = new Schema(
  {
    userId: stringOptions,
    dateFrom: stringOptions,
    dateTo: stringOptions,
    reportId: { type: Number, required: true },
    tax: { type: Number, required: true, default: 0 },
    financesAccountedAt: { type: Date, required: true },
    profit: { type: Number, required: true, default: 0 },
    margin: { type: Number, required: true, default: 0 },
    productCosts: { type: Number, required: true, default: 0 },
    insuranceFee: { type: Number, required: true, default: 0 },
    additionalInsuranceFee: { type: Number, required: true, default: 0 },
  },
  { _id: false },
);

var reportsSchema = new Schema({
  userId: stringOptions,
  reports: { type: [reportSchema], required: false },
  reportsWithAccountedFinances: { type: [reportsWithAccountedFinancesSchema], required: false },
  schemaVersion: { type: Number },
});

export default reportsSchema;
